#!/bin/sh

cat <<EOF
{
  "HCLOUD_TOKEN": "${HCLOUD_TOKEN}",
  "HCLOUD_SSH_KEY": "${HCLOUD_SSH_KEY}",
  "AWS_ACCESS_KEY_ID": "${AWS_ACCESS_KEY_ID}",
  "AWS_SECRET_ACCESS_KEY": "${AWS_SECRET_ACCESS_KEY}"
}
EOF
