#!/bin/sh

WG_SERVER_PRIVATE_KEY=$(wg genkey)
WG_SERVER_PUBLIC_KEY=$(echo ${WG_SERVER_PRIVATE_KEY} | wg pubkey)
WG_CLIENT_PRIVATE_KEY=$(wg genkey)
WG_CLIENT_PUBLIC_KEY=$(echo ${WG_CLIENT_PRIVATE_KEY} | wg pubkey)
cat <<EOF
{
  "WG_SERVER_PRIVATE_KEY": "${WG_SERVER_PRIVATE_KEY}",
  "WG_SERVER_PUBLIC_KEY": "${WG_SERVER_PUBLIC_KEY}",
  "WG_CLIENT_PRIVATE_KEY": "${WG_CLIENT_PRIVATE_KEY}",
  "WG_CLIENT_PUBLIC_KEY": "${WG_CLIENT_PUBLIC_KEY}"
}
EOF
